name: Azure Static Web Apps CI/CD

on: 
  workflow_dispatch:
  release:
    types: [created]
  
  repository_dispatch:
    types: [content]
    
env:
  NODE_VERSION: "18.x"
  STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn install, generate
        run: |
          yarn
          yarn generate
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_MUSHROOM_0D0C6DA03 }}
          action: "upload"
          app_location: ".output/public" # App source code path